const mockEvents = {
  "city": {
    "id": 1007700,
    "city": "München",
    "lat": 48.14,
    "lon": 11.58,
    "state": "",
    "country": "de",
    "zip": "meetup3",
    "member_count": 1257
  },
  "events": [
    {
      "created": 1581676443000,
      "duration": 5400000,
      "id": "268705764",
      "name": "Running Kubernetes on Azure",
      "rsvp_limit": 80,
      "date_in_series_pattern": false,
      "status": "upcoming",
      "time": 1583429400000,
      "local_date": "2020-03-05",
      "local_time": "18:30",
      "updated": 1581927279000,
      "utc_offset": 3600000,
      "waitlist_count": 0,
      "yes_rsvp_count": 54,
      "venue": {
        "id": 25766821,
        "name": "medialesson - Büro München",
        "lat": 48.1531,
        "lon": 11.58358,
        "repinned": true,
        "address_1": "Leopoldstr. 8-10",
        "address_2": "c/o Nutrion Coworking Space",
        "city": "München",
        "country": "de",
        "localized_country_name": "Germany"
      },
      "group": {
        "created": 1520252901000,
        "name": "Software, Technology & Design Meetup München",
        "id": 27731423,
        "join_mode": "open",
        "lat": 48.14,
        "lon": 11.58,
        "urlname": "Software-Technology-Meetup-Munchen",
        "who": "Mitglieder",
        "localized_location": "München, Germany",
        "state": "",
        "country": "de",
        "region": "en_US",
        "timezone": "Europe/Berlin"
      },
      "link": "https://www.meetup.com/Software-Technology-Meetup-Munchen/events/268705764/",
      "description": "<p>In this session Mohit Chhabra will give you insights how to run real apps on the most popular container orchestrator in Azure.<\/p> <p>We’ll review a high-level overview of the Azure Kubernetes Service (AKS) service and Azure Container Registry (ACR). We will start with the basic concepts of Kubernetes followed by understanding how AKS is different from the vanilla Kubernetes. Finally we'll be setting up and deploying a real world app on AKS. Feel free to follow along!<\/p> <p>Our speaker Mohit is working as Software Engineer at medialesson GmbH, Germany. He is currently Microsoft Most Valuable Professional for Microsoft Azure and former leader of BDotnet (India's Biggest offline community). He has delivered more than 50 sessions in the community and international conferences. Prior to this, Mohit was Microsoft Student Partner and Mozilla Student Representative. He was also India's first Azure Champion and the first person to intern in Microsoft Technology Center.<\/p> <p>This meetup will be hosted by medialesson, food and drinks will be provided. The session language is English. Please make sure you update your RSVP status 24h in advance so we don't waste any food!<\/p> ",
      "how_to_find_us": "The entry to building No. 8 is directly accessible from Leopoldstr. near Siegestor, walk down the broad spiral stairs down to the basement and enter trough the first glass door on the right hand.",
      "visibility": "public",
      "member_pay_fee": false
    },
    {
      "created": 1579163951000,
      "duration": 10800000,
      "id": "ddhzmrybchbbc",
      "name": "Drupal User Group Munich @Acquia",
      "rsvp_limit": 20,
      "date_in_series_pattern": false,
      "status": "upcoming",
      "time": 1589994000000,
      "local_date": "2020-05-20",
      "local_time": "19:00",
      "updated": 1582734701000,
      "utc_offset": 7200000,
      "waitlist_count": 0,
      "yes_rsvp_count": 2,
      "venue": {
        "id": 26867219,
        "name": "Acquia GmbH",
        "lat": 48.14321,
        "lon": 11.538675,
        "repinned": false,
        "address_1": "Erika-Mann-Straße 53",
        "city": "München",
        "country": "de",
        "localized_country_name": "Germany"
      },
      "group": {
        "created": 1410086988000,
        "name": "München Drupal User Group Meetup",
        "id": 16845232,
        "join_mode": "open",
        "lat": 48.14,
        "lon": 11.58,
        "urlname": "Munchen-Drupal-User-Group-Meetup",
        "who": "Drupalistas",
        "localized_location": "München, Germany",
        "state": "",
        "country": "de",
        "region": "en_US",
        "timezone": "Europe/Berlin"
      },
      "link": "https://www.meetup.com/Munchen-Drupal-User-Group-Meetup/events/ddhzmrybchbbc/",
      "description": "<p>Das Meetup ist sowohl für Drupal-AnwenderInnen, -EntwicklerInnnen, -EinsteigerInnen als auch Professionals geeignet. Wir reden nicht nur über Drupal, sondern auch über Community, React, Vue.js, Docker, Symfony, PHP, UX und viele andere Dinge. Andere Communities sind bei uns herzlich Willkommen!<\/p> <p>The meetup is for any level of Drupal user. We are not talking Drupal only but also about community, React, Vue.js, Docker Symfony, PHP, UX and much more stuff. Other communities are very welcome.<\/p> <p>---<br/>Vortrag 1 / Talk 1 - tbd<br/>---<br/>Vortrag 2 /Talk 2 - tbd<br/>---<\/p> <p>Wir suchen immer nach interessanten Themen! Wenn du interessiert daran bist, einen Vortrag oder ein interessantes Projekt vorzustellen (deutsch oder englisch entscheidest du!), melde dich bei uns.<\/p> <p>Im Anschluss der Talks gibt es genügend Zeit für Diskussion und Networking. Wir sehen uns dort!<\/p> <p>---<\/p> <p>If you are interested in giving a talk or to speak about a interesting project, drop us a line. We are always looking for talks.<\/p> <p>Followed by discussion and networking.<br/>See you there!<\/p> ",
      "visibility": "public",
      "member_pay_fee": false
    },
    {
      "created": 1580396975000,
      "duration": 2700000,
      "id": "268321786",
      "name": "Product Management Live Chat by Sandboxx Chief Product Officer",
      "date_in_series_pattern": false,
      "status": "upcoming",
      "time": 1586888100000,
      "local_date": "2020-04-14",
      "local_time": "20:15",
      "updated": 1580397318000,
      "utc_offset": 7200000,
      "waitlist_count": 0,
      "yes_rsvp_count": 3,
      "group": {
        "created": 1570531441000,
        "name": "Product School Munich",
        "id": 32863959,
        "join_mode": "open",
        "lat": 48.14,
        "lon": 11.58,
        "urlname": "Product-School-Munich",
        "who": "Members",
        "localized_location": "München, Germany",
        "state": "",
        "country": "de",
        "region": "en_US",
        "timezone": "Europe/Berlin"
      },
      "link": "https://www.meetup.com/Product-School-Munich/events/268321786/",
      "description": "<p>*** DISCLAIMER: This event is ONLINE ***<\/p> <p>Join in and get all your Product Management questions answered during our online event with Craig Zingerline, Chief Product Officer at Sandboxx.<\/p> <p>Some questions that will be answered include:<br/>1. What is the best part of being a Product Manager?<br/>2. What is the worst part of being a Product Manager?<br/>3. What do you look for in a Product Management resume and/or candidate?<br/>4. What was a difficult Product Manager interview question you’ve had? And how did you answer it?<br/>5. Have you ever felt like you didn’t understand the technology on a product? What did you do to compensate?<\/p> <p>Meet the Speaker: Craig Zingerline<\/p> <p>Craig is a 6-time founder and has advised and consulted for dozens of companies around Product Strategy and Growth. He's currently VP of Growth &amp; Travel at Sandboxx, and was previously Head of Growth at Upside Business Travel, Head of Product &amp; Growth at Red Tricycle, and CEO of Votion. Craig believes every company has growth potential to unlock, and that the Product Managers hold the keys to unlock that growth.<\/p> <p>*Entrance not guaranteed without valid ticket from Eventbrite<\/p> ",
      "visibility": "public",
      "member_pay_fee": false
    }
  ]
}

export { mockEvents };